<a href="https://colab.research.google.com/github/asrivasSW/AI-CLASS/blob/main/Parcial_repaso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as ap
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
#Crea un arreglo de 1 en 3x4

test = np.ones((3,4))

print(test)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#Imprime un arreglo de 0 en 2x2

test2 = np.zeros((2,2))

print(test2)

[[0. 0.]
 [0. 0.]]


In [5]:
#Accede a la segunda fila de la siguiente matriz

test3 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

fila = test3[1,:]

print(fila)

[ 6  7  8  9 10]


In [6]:
#Accede a la quinta columna de la matriz anterior

columna = test3[:,4]

print(columna)


[ 5 10]


In [14]:
#Realiza las operaciones basicas, con 2 matrices

a = np.array([[3,6,9,3,2],
             [9,4,5,6,3],
             [4,3,5,9,3]])

b = np.array([[3,1,5,6,7],
             [3,2,5,7,8],
             [4,3,4,5,1]])

suma = a + b

print("\nEste es resultado de suma\n", suma)

resta = a - b

print("\nResta\n", resta)

multiplicacion = a * b

print("\nMultipalicación\n",multiplicacion)

division = a / b

print("\nDivisión\n",division)

potencia = a ** b

print("\nPotencia\n",potencia)

raiz = np.sqrt(a)

print("\nRaiz\n",raiz)


Este es resultado de suma
 [[ 6  7 14  9  9]
 [12  6 10 13 11]
 [ 8  6  9 14  4]]

Resta
 [[ 0  5  4 -3 -5]
 [ 6  2  0 -1 -5]
 [ 0  0  1  4  2]]

Multipalicación
 [[ 9  6 45 18 14]
 [27  8 25 42 24]
 [16  9 20 45  3]]

División
 [[1.         6.         1.8        0.5        0.28571429]
 [3.         2.         1.         0.85714286 0.375     ]
 [1.         1.         1.25       1.8        3.        ]]

Potencia
 [[    27      6  59049    729    128]
 [   729     16   3125 279936   6561]
 [   256     27    625  59049      3]]

Raiz
 [[1.73205081 2.44948974 3.         1.73205081 1.41421356]
 [3.         2.         2.23606798 2.44948974 1.73205081]
 [2.         1.73205081 2.23606798 3.         1.73205081]]


In [20]:
# Bloque 1: NumPy - Arrays, Operaciones y Funciones


# 1. Creación de Arrays
arr1 = np.array([1, 3, 4, 5, 6])  # Array a partir de una lista
print("Array simple:", arr1)

# 2. Arrays Especiales
zeros = np.zeros((3, 3))  # Matriz 3x3 de ceros
ones = np.ones((2, 4))   # Matriz 2x4 de unos
arange = np.arange(0, 10, 2)  # Array de 0 a 10 (excluye 10) con paso 2
linspace = np.linspace(0, 1, 5)  # 5 números espaciados entre 0 y 1
print("\nMatriz de ceros (3x3):\n", zeros)
print("Matriz de unos (2x4):\n", ones)
print("Array con np.arange:", arange)
print("Array con np.linspace:", linspace)

# 3. Operaciones Elemento a Elemento
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nSuma elemento a elemento:", a + b)
print("Multiplicación elemento a elemento:", a * b)
print("Potencia elemento a elemento (a^2):", a ** 2)

# 4. Indexación y Slicing
print("\nPrimer elemento de arr1:", arr1[0])
print("Último elemento de arr1:", arr1[-1])
print("Subarray arr1[1:4]:", arr1[1:4])

# 5. Indexación en Matrices
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatriz 3x3:\n", matriz)
print("Elemento en (1,1):", matriz[1, 1])
print("Columna 0:", matriz[:, 0])
print("Fila 2:", matriz[2, :])

# 6. Funciones Estadísticas
print("\nSuma de arr1:", np.sum(arr1))
print("Media de arr1:", np.mean(arr1))
print("Máximo de arr1:", np.max(arr1))
print("Mínimo de arr1:", np.min(arr1))

# 7. Operaciones Matriciales
print("\nDimensiones de matriz:", matriz.shape)
print("Producto matricial (matriz.dot(matriz)):\n", matriz.dot(matriz))
print("Transpuesta de matriz:\n", matriz.T)

# 8. Normalización Min-Max
datos = np.array([10, 20, 30, 40, 50])
normalizados = (datos - np.min(datos)) / (np.max(datos) - np.min(datos))
print("\nDatos normalizados (Min-Max):", normalizados)

Array simple: [1 3 4 5 6]

Matriz de ceros (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriz de unos (2x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array con np.arange: [0 2 4 6 8]
Array con np.linspace: [0.   0.25 0.5  0.75 1.  ]

Suma elemento a elemento: [5 7 9]
Multiplicación elemento a elemento: [ 4 10 18]
Potencia elemento a elemento (a^2): [1 4 9]

Primer elemento de arr1: 1
Último elemento de arr1: 6
Subarray arr1[1:4]: [3 4 5]

Matriz 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento en (1,1): 5
Columna 0: [1 4 7]
Fila 2: [7 8 9]

Suma de arr1: 19
Media de arr1: 3.8
Máximo de arr1: 6
Mínimo de arr1: 1

Dimensiones de matriz: (3, 3)
Producto matricial (matriz.dot(matriz)):
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
Transpuesta de matriz:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Datos normalizados (Min-Max): [0.   0.25 0.5  0.75 1.  ]


In [19]:
# Bloque 2: Pandas - DataFrames, Series y Manipulación de Datos

# 1. Creación de DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# 2. Creación de Serie
serie = pd.Series([14, 18, 24, 25], name="Edades")
print("\nSerie:\n", serie)

# 3. Inspección de Datos
print("\nTipos de datos del DataFrame:\n", df.dtypes)
print("\nInformación del DataFrame:")
df.info()
print("\nValores como array NumPy:\n", df.values)

# 4. Selección de Columnas
print("\nSelección de columna 'Name':\n", df[["Name"]])

# 5. Añadir/Transformar Columna
df = df.assign(Age_Doubled=df["Age"] * 2)
print("\nDataFrame con nueva columna 'Age_Doubled':\n", df)

# 6. Filtrado de Datos
# Ejemplo con dataset 'tips' simulado
tips = pd.DataFrame({
    'total_bill': [16.99, 10.34, 21.01, 23.68, 24.59],
    'tip': [1.01, 1.66, 3.50, 3.31, 3.61],
    'smoker': ['No', 'No', 'No', 'Yes', 'Yes'],
    'time': ['Dinner', 'Lunch', 'Dinner', 'Dinner', 'Lunch'],
    'size': [2, 3, 3, 2, 4]
})
print("\nDataset 'tips':\n", tips)
print("\nFiltrado (total_bill < 15):\n", tips[tips["total_bill"] < 15])
print("\nFiltrado múltiple (time == 'Dinner' & tip > 3.00):\n",
      tips[(tips["time"] == "Dinner") & (tips["tip"] > 3.00)])
print("\nFiltrado múltiple (size >= 3 | total_bill > 20):\n",
      tips[(tips["size"] >= 3) | (tips["total_bill"] > 20)])

# 7. Modificar Índice
df.index = ['a', 'b', 'c']
print("\nDataFrame con nuevo índice:\n", df)

DataFrame:
       Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Serie:
 0    14
1    18
2    24
3    25
Name: Edades, dtype: int64

Tipos de datos del DataFrame:
 Name    object
Age      int64
dtype: object

Información del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

Valores como array NumPy:
 [['Alice' 25]
 ['Bob' 30]
 ['Charlie' 35]]

Selección de columna 'Name':
       Name
0    Alice
1      Bob
2  Charlie

DataFrame con nueva columna 'Age_Doubled':
       Name  Age  Age_Doubled
0    Alice   25           50
1      Bob   30           60
2  Charlie   35           70

Dataset 'tips':
    total_bill   tip smoker    time  size
0       16.99  1.01     No  Dinner     2
1       10.34  1.66     No   Lunch     3
2    

In [18]:
# Bloque 3: Estadística Descriptiva con Python, NumPy y Pandas


# Datos de ejemplo
data = [10, 20, 20, 30, 40, 50, 100]

# 1. Medidas de Tendencia Central
# Media
def promedio_lista(lista):
    return sum(lista) / len(lista)
print("Media (Python puro):", promedio_lista(data))
print("Media (NumPy):", np.mean(data))
print("Media (Pandas):", pd.Series(data).mean())

# Mediana
def mediana_lista(lista):
    sorted_list = sorted(lista)
    n = len(sorted_list)
    if n % 2 == 0:
        return (sorted_list[n//2 - 1] + sorted_list[n//2]) / 2
    else:
        return sorted_list[n//2]
print("\nMediana (Python puro):", mediana_lista(data))
print("Mediana (NumPy):", np.median(data))
print("Mediana (Pandas):", pd.Series(data).median())

# Moda
def moda_lista(lista):
    from collections import Counter
    counts = Counter(lista)
    return max(counts, key=counts.get)
print("\nModa (Python puro):", moda_lista(data))
print("Moda (Pandas):", pd.Series(data).mode()[0])

# 2. Medidas de Dispersión
# Rango
def rango_lista(datos):
    return max(datos) - min(datos)
print("\nRango (Python puro):", rango_lista(data))
print("Rango (NumPy):", np.max(data) - np.min(data))

# Desviación Estándar
print("\nDesviación Estándar (NumPy):", np.std(data, ddof=1))
print("Desviación Estándar (Pandas):", pd.Series(data).std())

# Correlación y Covarianza
df = pd.DataFrame({
    'income': [30000, 45000, 50000, 60000, 75000],
    'age': [25, 30, 35, 40, 45]
})
print("\nCorrelación (Pandas):\n", df[['income', 'age']].corr())
print("\nCovarianza (NumPy):\n", np.cov(df[['income', 'age']].values.T))

# 3. Prueba de Normalidad (Shapiro-Wilk)
normal_data = np.random.randn(100)  # Datos normales
print("\nPrueba Shapiro-Wilk (datos normales):", stats.shapiro(normal_data))
print("Prueba Shapiro-Wilk (data no normal):", stats.shapiro(data))
# Nota: p-value < 0.05 indica que los datos NO son normales

Media (Python puro): 38.57142857142857
Media (NumPy): 38.57142857142857
Media (Pandas): 38.57142857142857

Mediana (Python puro): 30
Mediana (NumPy): 30.0
Mediana (Pandas): 30.0

Moda (Python puro): 20
Moda (Pandas): 20

Rango (Python puro): 90
Rango (NumPy): 90

Desviación Estándar (NumPy): 30.237157840738178
Desviación Estándar (Pandas): 30.237157840738178

Correlación (Pandas):
           income       age
income  1.000000  0.987757
age     0.987757  1.000000

Covarianza (NumPy):
 [[2.8250e+08 1.3125e+05]
 [1.3125e+05 6.2500e+01]]

Prueba Shapiro-Wilk (datos normales): ShapiroResult(statistic=np.float64(0.9904453877202096), pvalue=np.float64(0.70059144110172))
Prueba Shapiro-Wilk (data no normal): ShapiroResult(statistic=np.float64(0.8427362098526461), pvalue=np.float64(0.10535215117208807))
